# Generated by Django 3.2.4 on 2021-06-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TecUser',
            fields=[
                ('uid', models.UUIDField()),
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=150)),
                ('dob', models.DateTimeField(max_length=40)),
                ('identity', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=50)),
            ],
        ),
    ]
