# Generated by Django 3.2.5 on 2021-07-14 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tecuser',
            name='dob',
            field=models.DateTimeField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tecuser',
            name='identity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tecuser',
            name='remarks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tecuser',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
