# Generated by Django 3.2.5 on 2021-07-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_appconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
