# Generated by Django 3.2.5 on 2021-08-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_logs_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appconfiguration',
            old_name='title',
            new_name='url',
        ),
    ]
